### ISSUE TITLE
Compile error due to missing com.google.guava dependency

### ISSUE THREAD

**Issue by zgyarmati** [rmohr/chroot-plugin#19]
After a fresh git clone on current master (5904208891f92911d1bc82d07f5f1118095e154c) the plugin fails to compile due to missing com.google.guava dependency, see mvn output below

$ mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building Chroot Plugin
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
[INFO] [hpi:validate {execution: default-validate}]
[INFO] [enforcer:display-info {execution: default}]
[INFO] Maven Version: 2.2.1
[INFO] JDK Version: 1.8.0_45 normalized as: 1.8.0-45
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 3.19.0-15-generic
[INFO] [localizer:generate {execution: default}]
[debug] execute contextualize
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 20 resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 14 source files to /home/zgyarmati/projects/chroot-plugin/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/tools/ChrootToolset.java:[26,29] error: package com.google.common.base does not exist
[ERROR] /home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/extensions/MockWorker.java:[26,32] error: package com.google.common.collect does not exist
[ERROR] /home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/util/ChrootUtil.java:[26,29] error: package com.google.common.base does not exist
[ERROR] /home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/util/ChrootUtil.java:[27,29] error: package com.google.common.base does not exist
[ERROR] /home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/util/ChrootUtil.java:[28,32] error: package com.google.common.collect does not exist
[ERROR] /home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/util/ChrootUtil.java:[40,25] error: cannot find symbol
[ERROR]  class ChrootUtil
/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/extensions/PBuilderWorker.java:[26,29] error: package com.google.common.base does not exist
[ERROR] /home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/extensions/PBuilderWorker.java:[27,32] error: package com.google.common.collect does not exist
[ERROR] error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider org.kohsuke.stapler.jsr269.ExportedBeanAnnotationProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
[INFO] 9 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/tools/ChrootToolset.java:[26,29] error: package com.google.common.base does not exist
/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/extensions/MockWorker.java:[26,32] error: package com.google.common.collect does not exist
/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/util/ChrootUtil.java:[26,29] error: package com.google.common.base does not exist
/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/util/ChrootUtil.java:[27,29] error: package com.google.common.base does not exist
/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/util/ChrootUtil.java:[28,32] error: package com.google.common.collect does not exist
/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/util/ChrootUtil.java:[40,25] error: cannot find symbol
 class ChrootUtil
/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/extensions/PBuilderWorker.java:[26,29] error: package com.google.common.base does not exist
/home/zgyarmati/projects/chroot-plugin/src/main/java/org/jenkinsci/plugins/chroot/extensions/PBuilderWorker.java:[27,32] error: package com.google.common.collect does not exist
error: Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider org.kohsuke.stapler.jsr269.ExportedBeanAnnotationProcessor could not be instantiated: java.lang.NoClassDefFoundError: com/google/common/collect/Multimap

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8 seconds
[INFO] Finished at: Sun Jul 05 20:34:10 CEST 2015
[INFO] Final Memory: 72M/700M
[INFO] ------------------------------------------------------------------------

**Comment by rmohr** [comment]
See #20 for details
