### ISSUE TITLE
how to copy the generated binaries from chroot build environment to base vm(jenkins) 

### ISSUE THREAD

**Issue by ngundu** [rmohr/chroot-plugin#22]
I have installed and configured the chroot plugin in Jenkins and as build is successful where I have to copy the binaries from chroot environment to the base vm

**Comment by labs-stellios** [comment]
To clarify, you want to copy the build output out of the chroot?

@ngundu, can you share your config in `Manage-Jenkins->Configure System` and  Job->Configure?  I don't have a label in my `Manage Jenkins -> Chroot Environment`s as shown here:
https://wiki.jenkins-ci.org/display/JENKINS/chroot+Plugin

![screenshot 2015-08-11 10 11 43](https://cloud.githubusercontent.com/assets/8261825/9204369/b77ebcb6-4011-11e5-827a-6376b8be52ce.png)

![screenshot 2015-08-11 10 12 36](https://cloud.githubusercontent.com/assets/8261825/9204368/b77bfd14-4011-11e5-9c1e-26e474c3941a.png)

You may be able to script it.

```
sudo chroot my-chroot
cp path/to/build-output /tmp
exit
cp my-chroot/tmp/build-output /path/outside/chroot
```

and then you may also need to allow the jenkins user to use chroot as sudo without a password:

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install dchroot
which chroot
sudo vim /etc/sudoers
# Add the following:

# Allow the jenkins user to use pbuilder
jenkins ALL=(ALL) NOPASSWD: /usr/sbin/pbuilder, /usr/sbin/chroot
```

**Comment by kodekarl** [comment]
To copy built binaries out of the chroot environment, there are two good ways:
1. Use Jenkins' built-in feature to archive artifacts. These can then be downloaded either through the UI or in downstream jobs using a "Copy artifacts" plug-in.
2. The chroot environment build step can place files anywhere inside the build workspace, and these files can be accessed by subsequent build steps in the same job.

**Comment by labs-stellios** [comment]
@kodekarl , sorry to hijack the issue.  might you know anything about `.pbuilderrc` in this [issue](https://github.com/rmohr/chroot-plugin/issues/23)

**Comment by kodekarl** [comment]
One thought: If by "build is successful" you mean that your job runs e.g. "make install" and you then want to find and copy the installed binary out of the chroot - here's a suggestion:
Your build tool (autoconf, cmake, ...) may support installing your software in a different location than default (e.g. with autoconf you do `configure --prefix=X` and it installs under X). You can use this to have the software installed inside your job workspace -- I've used this feature many times, and usually choose a subdir in the workspace named "prefix".
Your tool (make install?) will then place all files in subdirs under X, and you can use them in later steps, or archive them as artifacts, or create a package from it, or ...

**Comment by rmohr** [comment]
The right thing to do here is to either build in the current location inside the chroot environment (the current location in there is the same location, as the workspace root directory) as @corecache  suggested, or by copying all relevant data inside the chroot as a last step into the working directory before the chroot buildstep is done.

To avoid misinterpretations, with other words: When not changing the directory inside the chroot build step, you are still in the workspace of the current job. Just make sure that your relevant data is there before the build step finishes.

I am closing this, feel free to reopen if this does not answer your question.
