### ISSUE TITLE
FATAL: The node Jenkins is not correctly setup up for pbuilder

### ISSUE THREAD

**Issue by labs-stellios** [rmohr/chroot-plugin#23]
I'm trying to build a basic hello-world in C within a chroot.  At this point, I'm not even running `make`.  I'm just trying to enter the chroot.

The feature I want is exactly what is described [here](http://blog.steve.org.uk/continuous_integration_that_uses_chroots_.html):
>Creates a new debootstrap-based chroot.
>Installs build-essential, git, make, etc.
>Fetches the source.
>Runs make.
>Copies the build-output to a safe location OUTSIDE the chroot
>Cleans up.

I seem to have an issue with my configuration.  I'm trying to follow the [wik](https://wiki.jenkins-ci.org/display/JENKINS/chroot+Plugin)i as closely as possible:

```
$ uname -r
3.16.0-30-generic

$ which pbuilder
/usr/sbin/pbuilder

# In /etc/sudoers:
# Allow the jenkins user to use pbuilder
jenkins ALL=(ALL) NOPASSWD: /usr/sbin/pbuilder
```
![screenshot 2015-08-11 11 02 17](https://cloud.githubusercontent.com/assets/8261825/9206096/af12ffe8-401a-11e5-9aad-297163771b2d.png)
![screenshot 2015-08-11 11 03 05](https://cloud.githubusercontent.com/assets/8261825/9206095/af123b76-401a-11e5-9a04-51833ef5ef73.png)

Environment:
Jenkins: v1.624
chroot plugin: v0.1.4
GitHub plugin: v1.12.1

The console output from the build seems to also be cloning the test repo before the chroot is created and entered:

```
Started by timer
Building in workspace /var/lib/jenkins/workspace/Hello Jenkins
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@github.com:XXXXXX/hello-jenkins.git # timeout=10
Fetching upstream changes from git@github.com:com:XXXXXX/hello-jenkins.git
 > git --version # timeout=10
using GIT_SSH to set credentials com:XXXXXX build bot
 > git -c core.askpass=true fetch --tags --progress git@github.com:com:XXXXXX/hello-jenkins.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision c1205d804fd3528f8a85ba0767d73e72ad3068ba (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f c1205d804fd3528f8a85ba0767d73e72ad3068ba
 > git rev-list c1205d804fd3528f8a85ba0767d73e72ad3068ba # timeout=10
FATAL: The node Jenkins is not correctly setup up for pbuilder
java.io.IOException: The node Jenkins is not correctly setup up for pbuilder
	at org.jenkinsci.plugins.chroot.tools.ChrootToolset.forNode(ChrootToolset.java:93)
	at org.jenkinsci.plugins.chroot.builders.ChrootBuilder.perform(ChrootBuilder.java:145)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Sending e-mails to: XXXXXX
Finished: FAILURE
```

This is a single linux box (only a single Jenkins master node).

**Comment by labs-stellios** [comment]
This is at least partially solved by removing the contents of the `label` field.  See comments about labels in [this](https://github.com/rmohr/chroot-plugin/issues/3) issue.

![a](https://cloud.githubusercontent.com/assets/8261825/9231593/d081cca4-40dd-11e5-804b-4a1233569789.png)

My updated System and Job configurations are now:
![screenshot 2015-08-12 10 45 49](https://cloud.githubusercontent.com/assets/8261825/9231858/52f9dcb6-40df-11e5-9684-0bae4b917d13.png)

![screenshot 2015-08-12 10 45 17](https://cloud.githubusercontent.com/assets/8261825/9231861/5442b804-40df-11e5-93f3-a5163ca2160b.png)


 
The new error is also related to pbuilder.  The console output for the build shows:

```
$ sudo /usr/sbin/pbuilder --create --basetgz /var/lib/jenkins/pbuilder/my-trusty-pbuilder.tgz --extrapackages "software-properties-common sudo wget"
W: /var/lib/jenkins/.pbuilderrc does not exist
```

Then the build hangs forever.  I confirmed that `/var/lib/jenkins/.pbuilderrc` in fact does NOT exist.

**Comment by kodekarl** [comment]
Everything down to the mount failure is normal. My builds do the same (takes a few minutes to initialize, hardlink failures, etc).
The clue is in the error message "mount: special device /var/lib/jenkins/workspace/Hello does not exist", while your job appears to be called "Hello Jenkins". Apparently there's a problem with chroot plug-in and job names with a space character in them. I suspect that other tools/plug-ins may have similar problems and advise you to not use space in job names.
Try renaming the job to "Hello_Jenkins" and see if that works better?

**Comment by kodekarl** [comment]
The warning about .pbuilderrc is benign, if annoying. You can just make an empty one to get rid of the warning. For our builds, I need not only the "main" repository, but also "universe" and "multiverse" (IIRC), and there's a special variable that I set in .pbuilderrc to enable that - so I have one ;-)

**Comment by kodekarl** [comment]
Ah, found this:
> Setting pbuilder up is very easy. Edit ~/.pbuilderrc and add the following line to it:
> COMPONENTS="main universe multiverse restricted"

here: https://wiki.ubuntu.com/UbuntuDevelopment/GettingSetUp#Setting_up_pbuilder
Of course, you can choose whichever components you need for your build. Default is to only have "main".

**Comment by labs-stellios** [comment]
First success!  Thank you for helping isolate what is normal!  Yes the whitespace in the name was an issue.  Creating an empty  rc configuration file `/var/lib/jenkins/.pbuilderrc` removed that warning.

**Comment by kodekarl** [comment]
:ok_hand:

**Comment by imcginnis** [comment]
Thanks! This thread was super helpful. In addition to the above, it turned out that `Defaults requiretty` was enabled in my `/etc/sudoers` file. I fixed it by adding the below to that file:

`Defaults:jenkins !requiretty`
