### ISSUE TITLE
Pbuilder arguments get truncated

### ISSUE THREAD

**Issue by corecache** [rmohr/chroot-plugin#4]
As written in #3, with the current commit 24a6c9bdc6b0540c109ea1008bc34db0ca0511b4 the chroot environment arguments für pbuilder get somehow truncated down the way till execution.

e.g:
--distribution myDist --mirror http://my-repo.local/myos --debootstrapopts --no-check-gpg --debootstrapopts --variant=minbase --debootstrapopts --include=my-repo-archive-keyring --allow-untrusted --othermirror 'deb http://my-repo.local/debian wheezy main contrib non-free' 

Works on the shell with pbuilder. Using it as parameters thru jenkins fails with:
>Type ''deb' is not known on line 1 in source list /etc/apt/sources.list

NOTE: the quotes in the error message, it says ( 'deb ) is not a valid start. 

Removing the quotes from the arguments field in Jenkins does not help as --othermirror only gets "deb" as arguments (shell interpolation)

**Comment by corecache** [comment]
I suspect:
>src/main/java/org/jenkinsci/plugins/chroot/extensions/PBuilderWorker.java:86:            cmd.add(property.getSetupArguments().split("\\s+"));

**Comment by rmohr** [comment]
Yes you are right! Thank you for moving this into a separate issue!

**Comment by rmohr** [comment]
Should be fixed with abc9334.

I have tested it with an extra arguments string of
```
--components 'main restricted universe multiverse'
```
and it worked.

@corecache Could you please also verify that it works?

**Comment by corecache** [comment]
@rmohr Its fixed:

```
W: /root/.pbuilderrc does not exist
debconf: delaying package configuration, since apt-utils is not installed

$ sudo /usr/sbin/pbuilder --update --basetgz /var/lib/jenkins/workspace/chroot_test/foobar/foobar.tgz
W: /root/.pbuilderrc does not exist

$ whoami
$ id -n -g jenkins
$ id -u jenkins
$ id -g jenkins
$ sudo /usr/sbin/pbuilder --execute --bindmounts /var/lib/jenkins/workspace/chroot_test --basetgz /var/lib/jenkins/workspace/chroot_test/foobar/foobar.tgz -- /var/lib/jenkins/workspace/chroot_test/chroot1932569332482682706.sh
W: /root/.pbuilderrc does not exist
I: Building the build Environment
I: extracting base tarball [/var/lib/jenkins/workspace/chroot_test/foobar/foobar.tgz]
I: creating local configuration
I: copying local configuration
I: mounting /proc filesystem
I: mounting /dev/pts filesystem
I: Mounting /var/lib/jenkins/workspace/chroot_test
I: policy-rc.d already exists
I: Obtaining the cached apt archive contents
+ cd /var/lib/jenkins/workspace/chroot_test
I: Copying back the cached apt archive contents
I: unmounting /var/lib/jenkins/workspace/chroot_test filesystem
I: unmounting dev/pts filesystem
I: unmounting proc filesystem
I: cleaning the build env 
I: removing directory /var/cache/pbuilder/build//9505 and its subdirectories
Finished: SUCCESS
```

Thank you very much for that fix! :)

**Comment by rmohr** [comment]
Great thanks for verifying!
